// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUhqecIaQoAz4hqGYOSxVt-2kSBfMs04A',
    appId: '1:226219543442:web:13f72b4efb351fbbc38f4b',
    messagingSenderId: '226219543442',
    projectId: 'ders-6baeb',
    authDomain: 'ders-6baeb.firebaseapp.com',
    storageBucket: 'ders-6baeb.firebasestorage.app',
    measurementId: 'G-9YCJCEFHMV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUFIo03ztr32xAAil8pkJEGWBlTXNzQKg',
    appId: '1:226219543442:android:3cfc3b152ba0ba05c38f4b',
    messagingSenderId: '226219543442',
    projectId: 'ders-6baeb',
    storageBucket: 'ders-6baeb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyyrYHWzZtsXyXUUX_PJf9vOmyspIYKSI',
    appId: '1:226219543442:ios:b0c92a981a24c055c38f4b',
    messagingSenderId: '226219543442',
    projectId: 'ders-6baeb',
    storageBucket: 'ders-6baeb.firebasestorage.app',
    iosBundleId: 'com.example.dersApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyyrYHWzZtsXyXUUX_PJf9vOmyspIYKSI',
    appId: '1:226219543442:ios:b0c92a981a24c055c38f4b',
    messagingSenderId: '226219543442',
    projectId: 'ders-6baeb',
    storageBucket: 'ders-6baeb.firebasestorage.app',
    iosBundleId: 'com.example.dersApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUhqecIaQoAz4hqGYOSxVt-2kSBfMs04A',
    appId: '1:226219543442:web:633864ee8fb915e5c38f4b',
    messagingSenderId: '226219543442',
    projectId: 'ders-6baeb',
    authDomain: 'ders-6baeb.firebaseapp.com',
    storageBucket: 'ders-6baeb.firebasestorage.app',
    measurementId: 'G-MBB4VPG4YJ',
  );
}
